title:
email:
description: >- 
  Alright
baseurl: "/"
url: "https://smrz.dev"
github_username:  wltsmrz
# theme: minima
# remote_theme: chesterhow/tale
remote_theme: b2a3e8/jekyll-theme-console
permalink:    /:year-:month-:day/:title
plugins:
  - jekyll-remote-theme

